WORD_SIZE = 16
WORD_SIZE_WITH_ECC = 21
WORD_DOUBLE_SIZE = 32
WORD_DOUBLE_SIZE_WITH_ECC = 42
DISTANCE_ECC_ONE_MODULE = 5

ECC_NONE = 0
ECC_PARITY = 1
ECC_HAMMING = 2
ECC_LPC_WITHOUT_PARITY = 3
#ECC_DOUBLE_XOR = 4